---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


#  - name: update repository index
#    yum:
#      update_cache: yes
#    when: ansible_distribution in ["CentOS"]
#
#  - name: install apache2 package
#    yum:
#      name: httpd
#      state: latest
#    when: ansible_distribution == "CentOS"


#  - name: add php support for apache
#    yum:
#      name: php
#      state: latest
#    when: ansible_distribution == "CentOS"


