---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo (Ubuntu)
    tags: always
    package: 
        update_cache: yes
    changed_when: fasle
    when: ansible_distribution == "Ubuntu"

  - name: update repo (CentOS)
    tags: always
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:


  - name: add ssh key for test
    tags: always
    authorized_key:
      user: test
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkJj3HX2SqczhiE1AG1Z+rX7xQiuhOkw2k6LlbxzQMI test-key-for-ansible"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for ubuntu
    tags: webserver, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache2 (ubuntu)
    tags: apache2, web
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: change e-mail address for admin
    tags: apache2, ubuntu
    lineinfile: 
      path: /etc/apache2/apache2.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin sasha.bezin@gmail.com
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: restart apache2 (Ubuntu)
    tags: apache2, web, ubuntu
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default html file for site
    tags: apache2, webserver, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: istsall unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://hashicorp-releases.yandexcloud.net/terraform/1.9.7/terraform_1.9.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

#  - name: install apache and php for centos
#    package:
#      name:
#        - "{{ apache_package }}"
#        - "{{ php_package }}"
#      state: latest
#    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (ubuntu)
    tags: db
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: smb
    package:
      name: samba
      state: latest
#  - name: update repository index
#    yum:
#      update_cache: yes
#    when: ansible_distribution in ["CentOS"]
#
#  - name: install apache2 package
#    yum:
#      name: httpd
#      state: latest
#    when: ansible_distribution == "CentOS"


#  - name: add php support for apache
#    yum:
#      name: php
#      state: latest
#    when: ansible_distribution == "CentOS"


