---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    package: 
        upgrade: dist
        update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS)
    tags: always
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for ubuntu
    tags: webserver, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache2, webserver, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

#  - name: install apache and php for centos
#    package:
#      name:
#        - "{{ apache_package }}"
#        - "{{ php_package }}"
#      state: latest
#    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (ubuntu)
    tags: db
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: smb
    package:
      name: samba
      state: latest
#  - name: update repository index
#    yum:
#      update_cache: yes
#    when: ansible_distribution in ["CentOS"]
#
#  - name: install apache2 package
#    yum:
#      name: httpd
#      state: latest
#    when: ansible_distribution == "CentOS"


#  - name: add php support for apache
#    yum:
#      name: php
#      state: latest
#    when: ansible_distribution == "CentOS"


